### PR TITLE
[Bug][Update][Upstream]  Fix AscendPDBacked init for v0.4.5

### PR DESCRIPTION
**Pull request by marcobarlo**
## Summary
This PR fixes issue https://github.com/LMCache/LMCache-Ascend/issues/264 .

- Fix Ascend PD prefiller crash on peer connect:
  `AttributeError: 'AscendPDBackend' object has no attribute '_nixl_agent_lock'`.
- Replace stub `super()._ensure_peer_connection(...)` with an HCCL-native
  peer init (lazy channel connect + alloc REQ socket). Do **not** call
  upstream NIXL `_ensure_peer_connection`.
- Scope: `AscendPDSenderMixin._ensure_peer_connection` only
  (`lmcache_ascend/v1/storage_backend/pd/sender_mixin.py`).

## Why

- Upstream LMCache `7f60057c` (#2972, first in **v0.4.5**) added
  `_nixl_agent_lock` for the async NIXL worker thread.
- Ascend `AscendPDBackend.__init__` never calls `PDBackend.__init__`, so
  that lock is never created. HCCL already serializes via
  `transfer_channel._state_lock`; Ascend does not need `_nixl_agent_lock`.
- The old stub from #173 worked on LMCache ≤ v0.4.4 and broke after ≥ v0.4.5.

## Test plan

- [ ] Apply only this change (see `docs/fix_missing_nixl_agent_lock.diff`).
- [ ] Launch Ascend PD disagg (HCCL, prefiller + decoder).
- [ ] Send a request through the disagg proxy.
- [ ] Prefiller no longer raises `_nixl_agent_lock`; peer connect succeeds.

### CODE REVIEW

File: lmcache_ascend/v1/storage_backend/pd/sender_mixin.py [hunk 1]
```diff
@@ -258,13 +258,34 @@ def _ensure_peer_connection(
...
+
+        mem_alloc_socket = get_zmq_socket(
+            self.zmq_context,
+            receiver_mem_alloc_url,
+            "tcp",
+            zmq.REQ,
+            "connect",
         )
+        self.mem_alloc_sockets[receiver_id] = mem_alloc_socket
+        self.initialized_peers.add(receiver_id)
```
[the remark this answers is not in the document]
Comment (marcobarlo) [reply lmcache_ascend/v1/storage_backend/pd/sender_mixin.py:288]: @matthewygf I think this is not a valid comment as the peer_id is unique on sender side for any given rank of a D instance. Am I right?
